void func(void);
void connect_wifi(void);
void parse_json_data(const char *json_str); 
void lichess_api_get_email(void);
void lichess_api_init_client(void);
void lichess_api_make_move(char* move);
void lichess_api_stream_move_of_game();
void lichess_api_stream_event(void);
void lichess_api_create_game(bool rated, uint8_t minutes, uint8_t increment);
char* getColor();
char* get_username();